#! /usr/bin/bash

set -e

if [[ $(id -u) -ne 0 ]]; then
    echo "Error: You must be privileged to run this script." >&2
    exit 1
fi

print_help() {
    echo "root-nvim: Link the root's user neovim config to yours."
    echo "usage: $0 <username>"
}

username="$1"

if [[ "$username" == "" ]]; then
    print_help
    exit 1
elif ! id -u "$username" > /dev/null 2> /dev/null; then
    echo "User '$username' doesn't exists." >&2
    exit 1
fi

origin="/home/$username/.config/nvim"
destiny="/root/.config/nvim"

if [[ -d "$destiny" ]]; then
    echo "Error: '$destiny' already exists." >&2
    exit 1
elif [[ ! -d "$(dirname '$destiny')" ]]; then
    mkdir "$destiny"
fi

ln -s "$origin" "$destiny"

echo "Linked '$origin' to '$destiny'."
